import 'dotenv/config';

export const {
	PORT = PORT,
	DB_USER = DB_USER,
	DB_PASSWORD = DB_PASSWORD,
	DB_HOST = DB_HOST,
	DB_PORT = DB_PORT,
	DB_SERVICE = DB_SERVICE,

	SALT_ROUND = SALT_ROUND,
	SECRET_JWT_KEY = SECRET_JWT_KEY,
} = process.env;
